name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'refactor'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: '- No changes.'
version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['feature']
  patch:
    labels: ['fix', 'bug']
