name: 'Release Drafter'
on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main

jobs:
  release-drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Draft release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: "default-config.yml"
          versioning-strategy: "auto"
